version: "3.9"

services:
  postgres:
    image: postgres:13-alpine
    container_name: pgdb
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=serverlessdb
    volumes:
      - ./pg_vol=/var/lib/postgresql/data

  serverless-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - ./.env
